version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tickets_db
    environment:
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: tickets_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: